@startuml Deployment diagram
skinparam style strictuml

rectangle frontend as "Angular application"
rectangle backend as "Angular application"
rectangle GraphQl



@enduml

@startuml aaaa
skinparam style strictuml
skinparam TitleFontStyle plain
left to right direction
frame "**UC** aaaa"{
    actor Customer as A1
    
    rectangle "System" as s1{
         
        usecase uc1 as "interaction example"
        usecase uc2 as "interaction \n example"
        usecase uc3 as "multi
                    line
                    ---
                    interaction
                    ====
                    usecase"
    }
    
    ' The processor enforces the first connections.
    ' Use hidden connections to drive the overall flow.
    A1 -[hidden]-s1
    
    A1 --|> uc1 : <<needs>>
    interaction -left-> uc2
    uc2 ..> A1
}
@enduml